---
- name: Play to install and configure httpd
  hosts: localhost
  tasks:
    - name: Include httpd role
      ansible.builtin.include_role:
        name: my_ns.my_collection.httpd
        tasks_from: main.yml
