---
- name: Converge
  hosts: all
  gather_facts: false
  #become: true
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: my_collection.demo.demo_role
