---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    ansible_ssh_pipelining: no
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: my_ns.my_collection.httpd
...
