---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    images:
      - ubi8
      - ubi9
  tasks:
    # Developer must implement.

    - name: Stop a container
      containers.podman.podman_container:
        name: "{{ item }}"
        state: stopped
      ignore_errors: true
      loop: "{{ images }}"

    - name: Remove container
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      ignore_errors: true
      loop: "{{ images }}"

    - name: Remove an image
      containers.podman.podman_image:
        name: registry.access.redhat.com/{{ item }}/ubi-init
        state: absent
      ignore_errors: true
      loop: "{{ images }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
