---
- name: Install packages 
  ansible.builtin.yum:
   name: 
     - httpd
     - httpd-tools
   state: latest

- name: Create content 
  ansible.builtin.copy:
    content: "Hello, this is for molecule demo"
    dest: /var/www/html/index.html

- name: Start and enable service httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes 